=== rehau-eae/voximplant-transcribe/schema/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://rehau-eae.org/voximplant/schema.json",
  "title": "Response Format of transcriptiom",
  "description": "Формат возвращаемых данных после транскрибации разговора",
  "type": "object",
  "properties": {
    "DateTime": {
      "type": "string",
      "format": "date-time",
      "description": "Дата и время звонка"
    },
    "ExternalPhone": {
      "type": "string",
      "description": "Внешний телефонный номер, клиент"
    },
    "InternalPhone": {
      "type": "string",
      "description": "Внутренний телефонный номер, колл-центр"
    },
    "OperatorID": {
      "type": "string",
      "description": "ID оператора колл-центра, опционально"
    },
    "ConversationRecord": {
      "type": "string",
      "description": "Ссылка на запись аудио разговора"
    },
    "Dialog": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/DialogTextItem"
      },
      "description": "Транскрибированный диалог"
    },
    "SpecialPhrases": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/SpecialPhrase"
      }
    }
  },
  "definitions": {
    "DialogTextItem": {
      "type": "object",
      "properties": {
        "Time": {
          "type": "string",
          "format": "time",
          "description": "Время фразы"
        },
        "Side": {
          "type": "string",
          "enum": ["A", "B"],
          "description": "Сторона в диалоге, A - клиент, B - оператор"
        },
        "Text": {
          "type": "string",
          "description": "Текст фразы"
        }
      }
    },
    "SpecialGroup": {
      "type": "string",
      "enum": ["fraud", "claim", "prohibited for operator"]
    },
    "SpecialPhrase": {
      "type": "object",
      "properties": {
        "SpecialGroup": {
          "$ref": "#/definitions/SpecialGroup",
          "description": "Специальная группа распознавания"
        },
        "Side": {
          "type": "string",
          "enum": ["A", "B", "Both"],
          "description": "Сторона, произнесшая специальный текст"
        },
        "Phrase": {
          "type": "string",
          "description": "Произнесенная фраза"
        },
        "Count": {
          "type": "number",
          "description": "Произнесенное количество раз"
        }
      }
    }
  }
}

=== rehau-eae/voximplant-transcribe/examples/first.example.json
{
  "DateTime": "2022-10-30T11:30:00Z",
  "ExternalPhone": "+79099098899",
  "InternalPhone": "+78008000101",
  "OperatorID": "01",
  "ConversationRecord": "https:/sample.org/conversation/123456",
  "Dialog": [
    {
      "Time": "11:30:02Z",
      "Side": "A",
      "Text": "Здравствуйте, а куда я позвонил"
    },
    {
      "Time": "11:30:04Z",
      "Side": "B",
      "Text": "Добрый день, это Рехау"
    },
    {
      "Time": "11:30:06Z",
      "Side": "A",
      "Text": "У меня претензия"
    },
    {
      "Time": "11:30:08Z",
      "Side": "B",
      "Text": "Мы не виноваты"
    },
    {
      "Time": "11:30:10Z",
      "Side": "A",
      "Text": "Ну если не виноваты тогда до встречи в суде"
    },
    {
      "Time": "11:30:10Z",
      "Side": "B",
      "Text": "Да, мы готовы"
    }
  ],
  "SpecialPhrases": [
    { "SpecialGroup": "claim", "Side": "A", "Count": 1, "Phrase": "Претензия" },
    {
      "SpecialGroup": "prohibited for operator",
      "Side": "B",
      "Count": 1,
      "Phrase": "Мы не виноваты"
    }
  ]
}
